//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yycms.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBConnection : DbContext
    {
        public DBConnection()
            : base("name=DBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<yy_Banner> yy_Banner { get; set; }
        public virtual DbSet<yy_Banner_Type> yy_Banner_Type { get; set; }
        public virtual DbSet<yy_Fans_Wechat> yy_Fans_Wechat { get; set; }
        public virtual DbSet<yy_FriendLink> yy_FriendLink { get; set; }
        public virtual DbSet<yy_Keywords> yy_Keywords { get; set; }
        public virtual DbSet<yy_Message> yy_Message { get; set; }
        public virtual DbSet<yy_News> yy_News { get; set; }
        public virtual DbSet<yy_News_Schedule> yy_News_Schedule { get; set; }
        public virtual DbSet<yy_News_Type> yy_News_Type { get; set; }
        public virtual DbSet<yy_Page> yy_Page { get; set; }
        public virtual DbSet<yy_Page_Build_Config> yy_Page_Build_Config { get; set; }
        public virtual DbSet<yy_Page_Build_Task> yy_Page_Build_Task { get; set; }
        public virtual DbSet<yy_Page_Type> yy_Page_Type { get; set; }
        public virtual DbSet<yy_Permission> yy_Permission { get; set; }
        public virtual DbSet<yy_Permission_Type> yy_Permission_Type { get; set; }
        public virtual DbSet<yy_Photo> yy_Photo { get; set; }
        public virtual DbSet<yy_Photo_Item> yy_Photo_Item { get; set; }
        public virtual DbSet<yy_Photo_Type> yy_Photo_Type { get; set; }
        public virtual DbSet<yy_Platforms> yy_Platforms { get; set; }
        public virtual DbSet<yy_Product> yy_Product { get; set; }
        public virtual DbSet<yy_Product_Type> yy_Product_Type { get; set; }
        public virtual DbSet<yy_RedPack> yy_RedPack { get; set; }
        public virtual DbSet<yy_RedPack_Order> yy_RedPack_Order { get; set; }
        public virtual DbSet<yy_SinglePage> yy_SinglePage { get; set; }
        public virtual DbSet<yy_SiteSetting> yy_SiteSetting { get; set; }
        public virtual DbSet<yy_Spider> yy_Spider { get; set; }
        public virtual DbSet<yy_Spider_Log> yy_Spider_Log { get; set; }
        public virtual DbSet<yy_Spider_News> yy_Spider_News { get; set; }
        public virtual DbSet<yy_Statistics> yy_Statistics { get; set; }
        public virtual DbSet<yy_SynchronousTask> yy_SynchronousTask { get; set; }
        public virtual DbSet<yy_SysError> yy_SysError { get; set; }
        public virtual DbSet<yy_User> yy_User { get; set; }
        public virtual DbSet<yy_User_Type> yy_User_Type { get; set; }
        public virtual DbSet<yy_Video> yy_Video { get; set; }
        public virtual DbSet<yy_Video_Type> yy_Video_Type { get; set; }
    }
}
