//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yycms.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yy_Fans_Wechat
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public string openid { get; set; }
        public string nickname { get; set; }
        public string language { get; set; }
        public int sex { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string headimgurl { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Precision { get; set; }
        public string remark { get; set; }
        public string unionid { get; set; }
        public System.DateTime LOCATIONUpdateTime { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
