//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yycms.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yy_Page_Type
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public int IsMaster { get; set; }
        public long SupportPlatform { get; set; }
        public string Author { get; set; }
        public string Website { get; set; }
        public string QQ { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Summary { get; set; }
        public string Name { get; set; }
        public string Name_En { get; set; }
        public string Images { get; set; }
        public int Version { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
