//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yycms.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yy_Permission
    {
        public long ID { get; set; }
        public int TypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MenuName { get; set; }
        public string MenuLink { get; set; }
        public string PageName { get; set; }
        public string ShowIndex { get; set; }
        public string Icon { get; set; }
        public int IsShow { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
