//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yycms.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yy_Page
    {
        public long ID { get; set; }
        public string PageName { get; set; }
        public int BuildType { get; set; }
        public long TypeID { get; set; }
        public int PageKind { get; set; }
        public string SavePath { get; set; }
        public string ExtensionName { get; set; }
        public string Summary { get; set; }
        public string PageCode { get; set; }
        public int CanBuild { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    }
}
