//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yycms.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yy_RedPack_Order
    {
        public long ID { get; set; }
        public long red_packID { get; set; }
        public long UserID { get; set; }
        public long MechantID { get; set; }
        public long AgencyID { get; set; }
        public string re_openid { get; set; }
        public string mch_billno { get; set; }
        public string detail_id { get; set; }
        public long red_money { get; set; }
        public string status { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
