//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yycms.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yy_SynchronousTask
    {
        public long ID { get; set; }
        public int Platform { get; set; }
        public int BusinessType { get; set; }
        public long RelationID { get; set; }
        public int OperationType { get; set; }
        public int Status { get; set; }
        public int MaxTry { get; set; }
        public int TriedCount { get; set; }
        public string Data { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    }
}
