//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yycms.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yy_SiteSetting
    {
        public int ID { get; set; }
        public string SiteAddress { get; set; }
        public string Email { get; set; }
        public string Watermark { get; set; }
        public int EnabelWatermark { get; set; }
        public string MailServer { get; set; }
        public int MailPort { get; set; }
        public string MailAccount { get; set; }
        public string MailPassword { get; set; }
        public string SystemTopBar { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
