//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yycms.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yy_User
    {
        public long ID { get; set; }
        public string HeadImgUrl { get; set; }
        public string Mobile { get; set; }
        public string Mail { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public int Gender { get; set; }
        public int Role { get; set; }
        public string Permission { get; set; }
        public int CountryID { get; set; }
        public int ProvinceID { get; set; }
        public int DistrictID { get; set; }
        public int CityID { get; set; }
        public string Address { get; set; }
        public int LockFlag { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
