//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yycms.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yy_User_Type
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Permission { get; set; }
        public long PID { get; set; }
        public int IsShow { get; set; }
        public long ShowIndex { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
